### ISSUE TITLE
Still Able to copy and paste the content to search bar

### ISSUE THREAD

**Issue by Keatooon** [MarcoEidinger/cordova-disable-copy-paste#1]
Currently the app prevents from pasting to other apps.

**Problem:**
However, when:
1) The app crashes, it will not trigger the UIApplicationDidEnterBackgroundNotification event
2) The app is inactive, e.g. pull down the notification center and swipe to search bar, we are still able to paste the content in the search bar

**Suggested solution:**
1) Clear the clipboard in UIApplicationWillTerminateNotification and UIApplicationWillResignActiveNotification as well.

```
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(_clearClipboard)

                                                 name:UIApplicationDidEnterBackgroundNotification object:nil];

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(_clearClipboard)

                                                 name:UIApplicationWillResignActiveNotification object:nil];

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(_clearClipboard)

                                                 name:UIApplicationWillTerminateNotification object:nil];
```

**Comment by MarcoEidinger** [comment]
Hi, thank you very much for that finding and the corresponding pull request! I merged your pull request. Please note I also increased version to 1.0.1 and updated documentation (README) about your change. Happy Thanksgiving!

**Comment by Keatooon** [comment]
Great! Have a great day ahead. :D
